spring.application.name=Authentication-Service

server.port=8082

# ====== DB ======
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# LIQUIBASE
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.access-token-expiration-minutes=15
app.jwt.refresh-token-expiration-days=7
